export const siteConfig = {
  name: "AGNXI",
  tagline: "Agent Skills Directory",
  description: "Agent skills directory for coding assistants. Discover SKILL.md workflows, compare stars and updates, and install skills for Claude Code, Cursor, Windsurf, Amp, and more.",
  url: "https://agnxi.com",
  ogImage: "https://agnxi.com/og.png",
  twitterHandle: "@agnxi",
  links: {
    github: "https://github.com/doanbactam/agent-skills-directory",
    twitter: "https://x.com/agnxi",
  },
  keywords: [
    "agent skills",
    "agent skills directory",
    "agent skills catalog",
    "agent skills list",
    "SKILL.md",
    "coding assistant skills",
    "Claude Code skills",
    "amp code skills",
    "cursor skills",
    "antigravity skills",
    "github copilot skills",
    "openai codex skills",
    "openai codex cli skills",
    "windsurf skills",
    "ai coding tools",
    "developer tools",
  ],
}
